DROP DATABASE IF EXISTS `LAPOOL`;
Create database LAPOOL;
DROP TABLE IF EXISTS `LAPOOL`.`AUTHPROVIDER`;
CREATE TABLE  `LAPOOL`.`AUTHPROVIDER` (
    `ID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `PROVIDERID` varchar(100) NOT NULL, -- this is the userID given by social media sites
    `PROVIDERTYPE` int(10) NOT NULL,
    `NAME` varchar(250) NOT NULL,
    `EMAIL` varchar(250) NOT NULL,
    `PHONE` varchar(25) NOT NULL,
    `GENDER` char(1) NOT NULL,
    `STATUS` int(3) NOT NULL,
    `BIRTHDAY` datetime(6) NOT NULL,
    `CREATED` datetime(6) NOT NULL,
    `UPDATED` datetime(6) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6000 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `LAPOOL`.`TOKEN`;
CREATE TABLE  `LAPOOL`.`TOKEN` (
    `ID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `TOKEN` varchar(500) NOT NULL,
    `CREATED` datetime(6) NOT NULL,
    `UPDATED` datetime(6) NOT NULL,
    PRIMARY KEY (`ID`),
  CONSTRAINT `FK_TOKEN_AUTH` FOREIGN KEY (`ID`) 
  REFERENCES `AUTHPROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6000 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `LAPOOL`.`LOCATION`;
CREATE TABLE  `LAPOOL`.`LOCATION` (
  `ID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `LASTLAT` DOUBLE NOT NULL,
  `LASTLNG` DOUBLE NOT NULL,
  `RADIANSLNG` DOUBLE NOT NULL,
  `SINRADIANSLAT` DOUBLE NOT NULL,
  `COSRADIANSLAT` DOUBLE NOT NULL,
  `CREATED` datetime(6) ,
  `UPDATED` datetime(6) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FKEY_ID` FOREIGN KEY (`ID`) 
  REFERENCES `AUTHPROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `LAPOOL`.`FBUSERLOGIN`;
CREATE TABLE  `LAPOOL`.`FBUSERLOGIN` (
  `ID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `APPLICATIONID` varchar(50) NOT NULL,
  `LAST_REFRESH` datetime(6) NOT NULL,
  `TOKEN` varchar(500) NOT NULL,
  `EXPIRES` datetime(6) NOT NULL,
  `SOURCE` varchar(100) NOT NULL,
  `CREATED` datetime(6) NOT NULL,
  `UPDATED` datetime(6) NOT NULL,  
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ID` FOREIGN KEY (`ID`)
  REFERENCES `AUTHPROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `LAPOOL`.`PICKUPREQUEST`;
CREATE TABLE  `LAPOOL`.`PICKUPREQUEST` (
  `PICKID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `STATUS` int(3) NOT NULL,
  `ID` bigint(20) UNSIGNED NOT NULL,
  `PICKUPLAT` DOUBLE NOT NULL,
  `PICKUPLNG` DOUBLE NOT NULL,
  `DROPLAT` DOUBLE NOT NULL,
  `DROPLNG` DOUBLE NOT NULL,
   `GIRLSONLY` TINYINT(1) NOT NULL,
   `SMOKING` TINYINT(1) NOT NULL,
   `MUSIC` TINYINT(1) NOT NULL,
  `PICKADDRESS` varchar(250) NOT NULL,
  `DROPADDRESS` varchar(250) NOT NULL,
  `CREATED` datetime(6) NOT NULL,
  `UPDATED` datetime(6) NOT NULL,
  PRIMARY KEY (`PICKID`),
   KEY `FK_AUTH_ID` (`ID`),
  CONSTRAINT `FK_AUTH_ID` FOREIGN KEY (`ID`) 
  REFERENCES `AUTHPROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `LAPOOL`.`CHANNEL`;
CREATE TABLE  `LAPOOL`.`CHANNEL` (
  `CHANNELID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) NOT NULL UNIQUE,
  `DESCRIPTION` varchar(250) NOT NULL,
  `EMAILDOMAIN` varchar(250) NOT NULL,
  `STATUS` int(3) NOT NULL,
  `PARENTID` bigint(20) UNSIGNED,
  `CREATED` datetime(6) NOT NULL,
  `UPDATED` datetime(6) NOT NULL,
  PRIMARY KEY (`CHANNELID`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `LAPOOL`.`USERCHANNEL`;
CREATE TABLE  `LAPOOL`.`USERCHANNEL` (
  `USERCHANNELID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID` bigint(20) UNSIGNED NOT NULL,
  `CHANNELID` bigint(20) UNSIGNED NOT NULL,
  `EMAIL` varchar(250) NOT NULL,
  `VERIFICATIONKEY` varchar(250),
  `STATUS` int(3) NOT NULL,
  `DESCRIPTION` varchar(250),
  `CREATED` datetime(6) NOT NULL,
  `UPDATED` datetime(6) NOT NULL,
  PRIMARY KEY (`USERCHANNELID`),
  KEY `FK_AUTH` (`ID`),
  KEY `FK_CHANNEL` (`CHANNELID`),
  CONSTRAINT `FK_AUTH` FOREIGN KEY (`ID`)
  REFERENCES `AUTHPROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_CHANNEL` FOREIGN KEY (`CHANNELID`)
  REFERENCES `CHANNEL` (`CHANNELID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `LAPOOL`.`TRIP`;
CREATE TABLE  `LAPOOL`.`TRIP` (
  `TRIPID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `PICKID` bigint(20) UNSIGNED NOT NULL UNIQUE,
  `STATUS` int(3) NOT NULL,
  `STARTTIME`  datetime(6),
  `STOPTIME`   datetime(6),
  `HOSTSTARTLAT` DOUBLE,
  `HOSTSTARTLNG` DOUBLE,
  `HOSTSTOPLAT` DOUBLE,
  `HOSTSTOPLNG` DOUBLE,
  `GUESTSTARTLAT` DOUBLE,
  `GUESTSTARTLNG` DOUBLE,
  `GUESTSTOPLAT` DOUBLE,
  `GUESTSTOPLNG` DOUBLE,
  `PICKERAUTHID` bigint(20) UNSIGNED NOT NULL,
  `CREATED` datetime(6) NOT NULL,
  `UPDATED` datetime(6) NOT NULL,
  PRIMARY KEY (`TRIPID`),
  KEY `FK_PICKID` (`PICKID`),
  CONSTRAINT `FK_PICKID` FOREIGN KEY (`PICKID`) 
  REFERENCES `PICKUPREQUEST` (`PICKID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_PICKERAUTHID` FOREIGN KEY (`PICKERAUTHID`)
  REFERENCES `AUTHPROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



-- DROP TABLE IF EXISTS `LAPOOL`.`FEEDBACK`;
-- CREATE TABLE  `LAPOOL`.`FEEDBACK` (
--   `FEEDBACKID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
--   `TRIPID` bigint(20) UNSIGNED NOT NULL UNIQUE,
--   `ID` bigint(20) UNSIGNED NOT NULL,
--   `RATING` int(1),
--   `COMMENT` varchar(250),
--   `CREATED` datetime(6) NOT NULL,
--   `UPDATED` datetime(6) NOT NULL,
--   PRIMARY KEY (`FEEDBACKID`),
-- KEY `FK_TRIPID` (`TRIPID`), 
--   CONSTRAINT `FK_TRIPID` FOREIGN KEY (`TRIPID`)
--   REFERENCES `TRIP` (`TRIPID`) ON DELETE CASCADE ON UPDATE CASCADE,
-- KEY `FK_AUTHID` (`ID`), 
--   CONSTRAINT `FK_AUTHID` FOREIGN KEY (`ID`)
--   REFERENCES `AUTHPROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
-- ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `LAPOOL`.`MESSAGE`;
CREATE TABLE  `LAPOOL`.`MESSAGE` (
  `ID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `TRIPID` bigint(20) UNSIGNED NOT NULL,
  `FROMUSER` bigint(20) UNSIGNED NOT NULL,
  `TOUSER` bigint(20) UNSIGNED NOT NULL,
  `MESSAGE` varchar(250) NOT NULL,
  `CREATED` datetime(6) NOT NULL,
  `UPDATED` datetime(6) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_AUTH` (`FROMUSER`),
  KEY `FK_AUTH_2` (`TOUSER`),
  CONSTRAINT `FK_TRIP_MSG` FOREIGN KEY (`TRIPID`)
  REFERENCES `TRIP` (`TRIPID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_AUTH_MSG` FOREIGN KEY (`FROMUSER`)
  REFERENCES `AUTHPROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_AUTH_MSG_2` FOREIGN KEY (`TOUSER`)
  REFERENCES `AUTHPROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


------------------ version 1.4 SNAPSHOT - ARun on 10 May 2016 ---------

DROP TABLE IF EXISTS `LAPOOL`.`ACCOUNT`;
CREATE TABLE  `LAPOOL`.`ACCOUNT` (
  `ACCOUNTID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(250) NOT NULL,
  `CREATED` datetime(6) NOT NULL,
  `UPDATED` datetime(6) NOT NULL,
  PRIMARY KEY (`ACCOUNTID`)
) ENGINE=InnoDB AUTO_INCREMENT=500 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `LAPOOL`.`SYSTEMUSER`;
CREATE TABLE  `LAPOOL`.`SYSTEMUSER` (
`ID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
`USERNAME` varchar(250) UNIQUE NOT NULL,
`NAME` varchar(250) NOT NULL,
`EMAIL` varchar(250) NOT NULL,
`PHONE` varchar(100) NOT NULL,
`PASSWORD` varchar(250) NOT NULL,
`STATUS` int(3) NOT NULL,
`CREATED` datetime(6) NOT NULL,
`UPDATED` datetime(6) NOT NULL,
`ACCOUNTID` bigint(20) UNSIGNED NOT NULL,
`CHANNELID` bigint(20) UNSIGNED,
PRIMARY KEY (`ID`),
KEY `FK_ACC` (`ACCOUNTID`),
CONSTRAINT `FK_ACC` FOREIGN KEY (`ACCOUNTID`)
REFERENCES `ACCOUNT` (`ACCOUNTID`),
KEY `FK_CHAN` (`CHANNELID`),
CONSTRAINT `FK_CHAN` FOREIGN KEY (`CHANNELID`)
REFERENCES `CHANNEL` (`CHANNELID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `LAPOOL`.`PRIVILEGE`;
CREATE TABLE  `LAPOOL`.`PRIVILEGE` (
  `PRIVILEGEID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(250) NOT NULL,
  `CREATED` datetime(6) NOT NULL,
  `UPDATED` datetime(6) NOT NULL,
  PRIMARY KEY (`PRIVILEGEID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `LAPOOL`.`ACC_PRIV`;
CREATE TABLE  `LAPOOL`.`ACC_PRIV` (
  `ACCOUNTID` bigint(20) UNSIGNED NOT NULL,
  `PRIVILEGEID` bigint(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`ACCOUNTID`,`PRIVILEGEID`),
CONSTRAINT `FK_ACCID` FOREIGN KEY (`ACCOUNTID`)
REFERENCES `ACCOUNT` (`ACCOUNTID`),
CONSTRAINT `FK_PRIVID` FOREIGN KEY (`PRIVILEGEID`)
REFERENCES `PRIVILEGE` (`PRIVILEGEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO LAPOOL.ACCOUNT (DESCRIPTION, CREATED, UPDATED) 
VALUES ('Root', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
	
INSERT INTO LAPOOL.PRIVILEGE (DESCRIPTION, CREATED, UPDATED) 
VALUES ('View System User', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
	
INSERT INTO LAPOOL.PRIVILEGE (DESCRIPTION, CREATED, UPDATED) 
VALUES ('Add System User', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
	
INSERT INTO LAPOOL.PRIVILEGE (DESCRIPTION, CREATED, UPDATED) 
VALUES ('Edit System User', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
	
INSERT INTO LAPOOL.PRIVILEGE (DESCRIPTION, CREATED, UPDATED) 
VALUES ('View Channels', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
	
INSERT INTO LAPOOL.PRIVILEGE (DESCRIPTION, CREATED, UPDATED) 
VALUES ('Add Channel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
	
INSERT INTO LAPOOL.PRIVILEGE (DESCRIPTION, CREATED, UPDATED) 
VALUES ('Edit Channel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
	
INSERT INTO LAPOOL.ACC_PRIV (ACCOUNTID, PRIVILEGEID) 
VALUES (500, 1);
	
INSERT INTO LAPOOL.ACC_PRIV (ACCOUNTID, PRIVILEGEID) 
VALUES (500, 2);
	
INSERT INTO LAPOOL.ACC_PRIV (ACCOUNTID, PRIVILEGEID) 
VALUES (500, 3);
	
INSERT INTO LAPOOL.ACC_PRIV (ACCOUNTID, PRIVILEGEID) 
VALUES (500, 4);
	
INSERT INTO LAPOOL.ACC_PRIV (ACCOUNTID, PRIVILEGEID) 
VALUES (500, 5);
	
INSERT INTO LAPOOL.ACC_PRIV (ACCOUNTID, PRIVILEGEID) 
VALUES (500, 6);

#Replace below values according to your account
#Password is the hash value
INSERT INTO LAPOOL.SYSTEMUSER (USERNAME, `NAME`, EMAIL, PHONE, PASSWORD, STATUS, CREATED, UPDATED, ACCOUNTID, CHANNELID) 
	VALUES ('super', 'Super user', 'user@gmail.com', '91987654321', '6e884gfd3uj83267547h7vca8dc6292773603dghtg4d62a11ef78jer4', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 500, NULL);

-----------------------26June2016_2045IST---------------------

ALTER TABLE LAPOOL.TRIP ADD TRIPKEY VARCHAR(255)  after STOPTIME;
ALTER TABLE LAPOOL.TRIP ADD INDEX `TRIPKEY` (`TRIPKEY`);

DROP TABLE IF EXISTS `LAPOOL`.`TRIPLOCATION`;
CREATE TABLE  `LAPOOL`.`TRIPLOCATION` (
  `ID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `TRIPID` bigint(20) UNSIGNED NOT NULL,
  `AUTHID` bigint(20) UNSIGNED NOT NULL,
  `LAT` DOUBLE NOT NULL,
  `LNG` DOUBLE NOT NULL,
  `CREATED` datetime(6) NOT NULL,
  `UPDATED` datetime(6) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_TRIP` (`TRIPID`),
  KEY `FK_AUTH_1` (`AUTHID`),
  CONSTRAINT `FK_TRIP_PT` FOREIGN KEY (`TRIPID`)
  REFERENCES `TRIP` (`TRIPID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_AUTH_PT` FOREIGN KEY (`AUTHID`)
  REFERENCES `AUTHPROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `LAPOOL`.`ALERT`;
CREATE TABLE  `LAPOOL`.`ALERT` (
  `ID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `AUTHID` bigint(20) UNSIGNED NOT NULL,
  `TRIPID` bigint(20) UNSIGNED DEFAULT NULL,
   `ALERTKEY` VARCHAR(255) NOT NULL,
  `LAT` DOUBLE NOT NULL,
  `LNG` DOUBLE NOT NULL,
  `CREATED` datetime(6) NOT NULL,
  `UPDATED` datetime(6) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ALRT` (`TRIPID`),
  KEY `FK_ALRT_1` (`AUTHID`),
  CONSTRAINT `FK_TRIP_CT` FOREIGN KEY (`TRIPID`)
  REFERENCES `TRIP` (`TRIPID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_AUTH_CT` FOREIGN KEY (`AUTHID`)
  REFERENCES `AUTHPROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `LAPOOL`.`ALERTLOCATION`;
CREATE TABLE  `LAPOOL`.`ALERTLOCATION` (
  `ID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ALERTID` bigint(20) UNSIGNED DEFAULT NULL,
  `LAT` DOUBLE NOT NULL,
  `LNG` DOUBLE NOT NULL,
  `CREATED` datetime(6) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ALERT_KY` (`ALERTID`),
  CONSTRAINT `FK_ALERT_KY` FOREIGN KEY (`ALERTID`)
  REFERENCES `ALERT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

ALTER TABLE LAPOOL.PICKUPREQUEST ADD OPENTOALL TINYINT(1) NOT NULL after MUSIC;

-------------------------29 Sep 2016------------------------------------------------

ALTER TABLE LAPOOL.PICKUPREQUEST ADD SEATS INT(1) NOT NULL DEFAULT 1 AFTER OPENTOALL ;


------------------------- 1 Nov 2016------------------------------------------------

DROP TABLE IF EXISTS `LAPOOL`.`PATH`;
CREATE TABLE  `LAPOOL`.`PATH` (
  `ID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `AUTHID` bigint(20) UNSIGNED NOT NULL,
  `STARTLAT` DOUBLE NOT NULL,
  `STARTLNG` DOUBLE NOT NULL,
  `STARTRADIANSLNG` DOUBLE NOT NULL,
  `STARTSINRADIANSLAT` DOUBLE NOT NULL,
  `STARTCOSRADIANSLAT` DOUBLE NOT NULL,
  `DESTLAT` DOUBLE NOT NULL,
  `DESTRADIANSLNG` DOUBLE NOT NULL,
  `DESTSINRADIANSLAT` DOUBLE NOT NULL,
  `DESTCOSRADIANSLAT` DOUBLE NOT NULL,
  `DESTLNG` DOUBLE NOT NULL,
  `STARTADDRESS` varchar(250) NOT NULL,
  `DESTADDRESS` varchar(250) NOT NULL,
  `MON` TINYINT(1) NOT NULL,
  `TUE` TINYINT(1) NOT NULL,
  `WED` TINYINT(1) NOT NULL,
  `THU` TINYINT(1) NOT NULL,
  `FRI` TINYINT(1) NOT NULL,
  `SAT` TINYINT(1) NOT NULL,
  `SUN` TINYINT(1) NOT NULL,
  `STATUS` int(3) NOT NULL,
  `STARTTIME` time NOT NULL,
  `CREATED` datetime(6) NOT NULL,
  `UPDATED` datetime(6) NOT NULL,
  PRIMARY KEY (`ID`),
   KEY `FK_PATHAUTH_ID` (`AUTHID`),
  CONSTRAINT `FK_PATHAUTH_ID` FOREIGN KEY (`AUTHID`) 
  REFERENCES `AUTHPROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8;

-------------------------- 10 Feb 2017 -------------------------------

DROP TABLE IF EXISTS `LAPOOL`.`RATING`;
CREATE TABLE  `LAPOOL`.`RATING` (
  `ID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `TRIPID` bigint(20) UNSIGNED NOT NULL,
  `FROMUSER` bigint(20) UNSIGNED NOT NULL,
  `TOUSER` bigint(20) UNSIGNED NOT NULL,
  `RATING` int(3) NOT NULL,
  `COMMENTS` varchar(250) NOT NULL,
  `CREATED` datetime(6) NOT NULL,
  `UPDATED` datetime(6) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_AUTH` (`FROMUSER`),
  KEY `FK_AUTH_2` (`TOUSER`),
  CONSTRAINT `FK_TRIP_RT` FOREIGN KEY (`TRIPID`)
  REFERENCES `TRIP` (`TRIPID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_AUTH_RT` FOREIGN KEY (`FROMUSER`)
  REFERENCES `AUTHPROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_AUTH_RT_2` FOREIGN KEY (`TOUSER`)
  REFERENCES `AUTHPROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;